### ISSUE TITLE
security : URL redirection vuln

### ISSUE THREAD

**Issue by 0xIslamTaha** [0-complexity/openvcloud#259]
The following link has a URL redirection vuln
https://du-conv-2.demo.greenitglobe.com/logout?redirect_uri=http://www.google.com
as an example, It will redirect user to a google.com but the attacker can redirect the user to a malicious php reverse tcp script which allow the remote attacker to attack the user machine and have a total control over it.

**The impact of this vulnerability**
A remote attacker can redirect users from your website to a specified URL. This problem may assist an attacker to conduct phishing attacks, trojan distribution, spammers.

```
*Software*
JumpScale

    Core: 7.1.0b10
    Portal: 7.1.0b10

OpenvCloud

    Core: 2.1.0b10

OpenvStorage:

    openvstorage-backend-core: 1.6.1-eugene-updates.4-1
    alba: 0.8.1
    openvstorage-webapps: 2.6.1-eugene-updates.20-1
    openvstorage-backend-webapps: 1.6.1-eugene-updates.4-1
    openvstorage-core: 2.6.1-eugene-updates.20-1
    openvstorage-hc: 1.6.1-eugene-updates.4-1
    openvstorage-cinder-plugin: 1.1.1-eugene-updates.1-1
    openvstorage: 2.6.1-eugene-updates.20-1
    openvstorage-backend: 1.6.1-eugene-updates.4-1
    openvstorage-sdm: 1.5.1-eugene-updates.1-1

```
