### ISSUE TITLE
need support for clone machine 

### ISSUE THREAD

**Issue by ramezsaeed** [0-complexity/openvcloud#372]
# Env: be-g8-2
- when trying to clone a HALTED machine from the api it return (500 internal server error)
- Also got unexpected error when try to clone from the portal
  ![1](https://cloud.githubusercontent.com/assets/16083592/18252500/6ef1d1b2-7397-11e6-981f-fd8bccbf68c7.jpeg)
- however I can see the clone added to machine list
  ![2](https://cloud.githubusercontent.com/assets/16083592/18252651/207b4788-7398-11e6-8a22-4cc644dfcd36.jpg)
- and when open the cloned machine found that error
  ![3](https://cloud.githubusercontent.com/assets/16083592/18252725/9debf730-7398-11e6-991f-dbc8565f1a45.jpg)
# Test scenario:

```
    #. create 1 machine for account owner
    #. try to create machine with new user [user], should return 403
    #. try to clone created machine with new user [user], should return 403
    #. try to delete created machine with new user [user], should return 403
    #. add user to the cloudspace with write access
    #. create machine with new user [user], should succeed
    #. clone created machine with new user [user], should succeed
    #. delete created machine with new user [user], should succeed
```
# Test code:

https://github.com/0-complexity/G8_testing/blob/master/functional_testing/Openvcloud/ovc_master_hosted/ACL/a_basic_operations/acl_cloudspace_test.py#L507
# Software Versions:

```
JumpScale

    Core: 7.1.5b2
    Portal: 7.1.5b2

OpenvCloud

    Core: 2.1.5b2

OpenvStorage:

    openvstorage-backend-core: 1.7.2-rev.677.e6ec122-1
    alba: 0.9.18
    openvstorage-webapps: 2.7.2-rev.3884.42ef467-1
    openvstorage-backend-webapps: 1.7.2-rev.677.e6ec122-1
    openvstorage-core: 2.7.2-rev.3884.42ef467-1
    openvstorage-hc: 1.7.2-rev.677.e6ec122-1
    openvstorage-cinder-plugin: 1.2.2-rev.38.dcc3b76-1
    openvstorage: 2.7.2-rev.3884.42ef467-1
    openvstorage-backend: 1.7.2-rev.677.e6ec122-1
    openvstorage-sdm: 1.6.2-rev.330.f06c8de-1

```
