### ISSUE TITLE
create user offers gig and password by default

### ISSUE THREAD

**Issue by ramezsaeed** [0-complexity/openvcloud#373]
# Test scenario:
- open admin portal
- go to cloud brocker --> users
- click add user
  will see that the add user offer gig/passwd for u
  ![1](https://cloud.githubusercontent.com/assets/16083592/18270629/98c00762-7436-11e6-9fba-f5446bccb141.png)
# Software versions:

```
JumpScale

    Core: 7.1.5b2
    Portal: 7.1.5b2

OpenvCloud

    Core: 2.1.5b2

OpenvStorage:

    openvstorage-backend-core: 1.7.2-rev.677.e6ec122-1
    alba: 0.9.18
    openvstorage-webapps: 2.7.2-rev.3884.42ef467-1
    openvstorage-backend-webapps: 1.7.2-rev.677.e6ec122-1
    openvstorage-core: 2.7.2-rev.3884.42ef467-1
    openvstorage-hc: 1.7.2-rev.677.e6ec122-1
    openvstorage-cinder-plugin: 1.2.2-rev.38.dcc3b76-1
    openvstorage: 2.7.2-rev.3884.42ef467-1
    openvstorage-backend: 1.7.2-rev.677.e6ec122-1
    openvstorage-sdm: 1.6.2-rev.330.f06c8de-1

```
