### ISSUE TITLE
failed to create any machine template on environments with fargo

### ISSUE THREAD

**Issue by ramezsaeed** [0-complexity/openvcloud#379]
# Steps to reproduce:
- create account
- create cloud space
- create VM
- try to create template from this VM
- Job error :
  ![1](https://cloud.githubusercontent.com/assets/16083592/18316231/78f99406-7522-11e6-81df-86b9d112e7b0.png)
- Also now I cannot delete the account due to this failed created template
  ![2](https://cloud.githubusercontent.com/assets/16083592/18316433/3e597e1e-7523-11e6-8cf8-17384ece8e42.png)
# Expected behavior:
- this failed import in create template job should be fixed as fargo now has storage nodes and cpu nodes and this import should be done from storage node not cpu node.
- we should be able to delete the account even it has failed created template or VM.
# Software Versions (be-g8-3):

```
JumpScale

    Core: 7.1.5b2
    Portal: 7.1.5b2

OpenvCloud

    Core: 2.1.5b2

OpenvStorage:

    openvstorage-backend-core: 1.7.1-fargo.1-1
    openvstorage-health-check: 2.0.0-fargo.4-1
    alba: 0.9.19
    openvstorage-webapps: 2.7.1-fargo.4-1
    openvstorage-backend-webapps: 1.7.1-fargo.1-1
    openvstorage-core: 2.7.1-fargo.4-1
    openvstorage-hc: 1.7.1-fargo.1-1
    openvstorage-cinder-plugin: 1.2.1-fargo.1-1
    openvstorage: 2.7.1-fargo.4-1
    openvstorage-backend: 1.7.1-fargo.1-1
    openvstorage-sdm: 1.6.1-fargo.1-1
```
